name: Lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-function-linters:
    name: Run Function linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Dependencies in ./functions
        run: cd ./functions && npm ci && npm run lint
  run-public-linters:
    name: Run Public linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Dependencies in ./public
        run: cd ./public && npm ci && npm run lint